name: my workflow
on: push

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{github.event.repository}}
        uses: actions/checkout-retry@v4

      - name: show all files
        run: |
          ls 
          echo "total files are: " ls | wc -l
          

